# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'FMDB','~> 2.6.2'

pod 'FMDBMigrationManager', '~> 1.4.1'
target 'FMDBMigrationManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FMDBMigrationManager

  target 'FMDBMigrationManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FMDBMigrationManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
